### ISSUE TITLE
functional tests

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#12]
Test the cylc-rose functionality from within the cylc-rose repository (rather than in cylc-flow).

There are reasons why this should be done here:

* Nicer (less stuff in cylc-flow).
* Ensures we have the correct Cylc/Rose version bracketing.
* Allows us to have a testing matrix with different Rose/Cylc versions to ensure inter-compatibility.

Suggested approach, use pytest, avoid the filesystem where possible:

Split the existing functions into two to separate the cylc interface and fileparsing logic from the cylc-rose internals e.g:

```python
# the entry point
def get_rose_vars(dir_, opts):
    # illustrative and very non-functional :/
    config_tree = rose_config_tree_loader(dir_, opts)
    node = config_tree.node
    vars = _get_rose_vars(node)
    # ...
    config = {}
    config['whatever'] = vars['whatever']
    # ...
    return {'whatever': vars}

def _get_rose_vars(node):
    # ...
```

Then test the internal cylc-rose bits without the cylc-flow interface overheads and associated filesystem meddling:

```python
def test_env():
    # illustrative and very non-functional :/
    node = ConfigNode()
    node.set(['env', 'foo'], '1')
    assert _get_rose_vars(node) == {
        'whatever': {
             'foo' 1
        }
    }
```

**Comment by wxtim** [comment]
I now have a branch https://github.com/wxtim/cylc-rose/tree/rose-fileinstall-recording.convert-functional-tests where all but one of the functional tests have been moved to rose-cylc. This branch is, however, a branch of my post install feature branch.
