### ISSUE TITLE
what happens if `[jinja2:suite.rc]` and `[template variables]` are both set.

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#124]
**Describe the bug**
Investigate what happens if `[jinja2:suite.rc]` and `[template variables]` are both set.

**Steps to reproduce the bug**

Uncompress [rose-dep-warnings.tar.gz](https://github.com/cylc/cylc-rose/files/8323715/rose-dep-warnings.tar.gz) or manually create this workflow in `~/cylc-src/rose-dep-warnings`:

rose-suite.conf:
```ini
[jinja2:suite.rc]
GREETING="Hello"
[template variables]
GREETING="Mittyn Da"
```
flow.cylc:
```ini
#!jinja2
[scheduling]
    initial cycle point = 1066
    [[dependencies]]
        R1 = foo
[runtime]
    [[foo]]
        script = echo {{ GREETING }}
```
Then run
```
cylc graph rose-dep-warnings
cylc install rose-dep-warnings
cylc play rose-dep-warnings
cat ~/cylc-run/rose-dep-warnings/log/flow-files/flow.processed.cylc
```

**Expected behavior**
A warning should be printed to the effect that you shouldn't  use both sections.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
cylc-rose should raise an error and refuse to work.
