### ISSUE TITLE
retire ROSE_SITE

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#13]
> **Note:** This is in no way related to the `rose_stem` variable of the same name used on many sites. This is implemented within `rose_stem` via a different mechanism.

See this Discourse post - https://cylc.discourse.group/t/rose-site-is-anyone-using-it-outside-of-rose-stem/296

This functionality was quietly introduced and never gained traction. It doesn't really make sense for it to be implemented in the Rose layer, suggest moving it into Cylc as `CYLC_SITE` for configuration in the `global.cylc` file.

Should be accompanied by:

* A doc change to https://cylc.github.io/doc/build/7.8.7/html/suite-design-guide/portable-suites.html#the-jinja2-site-variable
* A change to Rose to remove the Rose configuration and a doc change to remove the env var entry.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Suggest attempting this with or after https://github.com/metomi/rose/issues/2448

**Comment by wxtim** [comment]
### Approach 1 (clean)
- [Rose] Delete exporting of `ROSE_SITE` from rose - warn that it's dead.
- [cylc-flow] Add `CYLC_SITE` to `global.cylc` spec, and add it to the variable dictionaries in `cylc/flow/parsec`.

### Approach 2 (feels nasty)
- [cylc-rose] if `ROSE_SITE` set provide conversion to to `CYLC_SITE`.
- [cylc-flow] Add `CYLC_SITE` to `global.cylc` spec, and add it to the variable dictionaries in `cylc/flow/parsec`. Make sure that this is done before the plugin is called to allow the plugin to over-ride.

**Comment by oliver-sanders** [comment]
Blocked by https://github.com/cylc/cylc-flow/issues/4108

**Comment by wxtim** [comment]
https://cylc.github.io/doc/build/7.8.7/html/suite-design-guide/portable-suites.html#the-jinja2-site-variable

Suggests that we have never really used these.

**Comment by oliver-sanders** [comment]
Good find, added that to the issue description.

**Comment by oliver-sanders** [comment]
Note the Rose feature is documented, just wasn't ever publicised:

http://metomi.github.io/rose/doc/html/api/environment-variables.html#envvar-ROSE_SITE

**Comment by dpmatthews** [comment]
> Blocked by [cylc/cylc-flow#4108](https://github.com/cylc/cylc-flow/issues/4108)

No need for this issue to be blocked given that we're not aware of anyone who used this feature
