### ISSUE TITLE
Tidy Log Directory

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#135]
**Describe the bug**

Cylc Rose currently leaves logs in `~/cylc-run/workflow/log/conf`. This should become `config` to be consistent with https://github.com/cylc/cylc-flow/issues/4802

**example**

```diff
~/cylc-run/temp1/run16/log/
-|-- conf
+|-- config
 |   |-- 20220404T111205-rose-suite.conf
 `-- install
     |-- 20220404T101204Z-install.log

```

**Comment by dpmatthews** [comment]
The timestamp should also include the timezone for consistency
