### ISSUE TITLE
Validate Rose Stem Suites

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#151]
**Describe exactly what you would like to see in an upcoming release**

Cylc Rose allows `cylc validate`, `cylc graph`, &c &c to access `rose-suite.conf` prior to workflow installation.
Rose stem cannot be used to validate a rose-stem suite.

Either by adding a `rose stem --validate` option, or by adding a `--stem` argument to the options available in Cylc enable validation, graphing &c of rose stem suites.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Duplicate of #150
