### ISSUE TITLE
Rose Stem Questions

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#182]
[draft]

Brain dump of thoughts about rose stem. 

## Boilerplate logic in `StemRunner.__init__`:

Are there ever actually cases where the kwargs are not the default kwargs? If not, why bother with all this logic?

## `jinja2:suite.rc` v. `template variables`:

SUITE_RC_PREFIX = `jinja2:suite.rc. Should it? Perhaps it should depend on Cylc version?

## Cases not covered by functional tests
- `self.opts.defines` not empty - does anyone ever do `rose stem --source=/foo --define-suites 'GREET="Hello"'`

## Can `value` in `_get_fcm_loc_layout_info` ever be false?
As far as I can tell line is always in the form `key:\svalue` or `key:\s`. If this is the case value will always have at least a single space and :. be true.

```python
     for line in fcm_loc_layout_output:
            key, value = line.split(":", 1)

            if key and value:
                ret[key] = value.strip()
```
@dpmatthews - is this reliable behavior from `fcm loc-layout`?

Why not:

```diff
     for line in fcm_loc_layout_output:
            key, value = line.split(":", 1)

-           if key and value:
-               ret[key] = value.strip()
+           ret[key] = value.strip()
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
> jinja2:suite.rc v. template variables:
>
> SUITE_RC_PREFIX = `jinja2:suite.rc. Should it? Perhaps it should depend on Cylc version?

This should probably reflect the section actually used in the `rose-suite.conf` file (defaulting to `template variables` is none set).
