### ISSUE TITLE
`PluginError` using `cylc install -D root-dir`

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-rose#217]
### Description

Tested in cylc-flow=8.0.3 only.

If you try to do a `cylc install` and have `root-dir=...` syntax in the command, carrying over from `pre v2 rose`, the install command will spit out a WARNING message, install the workflow, but then fail afterwards.

```
$ cylc install -D "root-dir{work}=somehost=/tmp" $PWD
2023-03-21T14:15:45+11:00 WARNING - You have set "rose-suite.conf[root-dir]", which is not supported at Cylc 8. Use `[install] symlink dirs` in global.cylc instead.
INSTALLED basic-workflow/run3 from /home/ColemanTom/roses/basic-workflow
PluginError: Error in plugin cylc.post_install.rose_opts
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

### Reproducible Example

Run `cylc install -D "root-dir{work}=somehost=/tmp"` for any workflow. You will get a WARNING and then an exception is thrown by `cylc-rose`.

### Expected Behaviour

WARNING should be an ERROR and `cylc install` should fail before the workflow is installed.

**Comment by wxtim** [comment]
@ColemanTom - Did you mean `cylc install -S "root-dir{work}=somehost=/tmp" $PWD` - I'm not sure that I'd expect `-D` to work, at least not in any useful way - I'd expect what you've done to be the equivelent of setting the `rose-suite.conf` as follows:

```toml
# rose-suite.conf
!opts = x, y, z
root-dir{work}=somehost=/tmp

[env]
...
```

Is that what you intend?
