### ISSUE TITLE
Environment variables set in rose-suite.conf should apply when the global config is loaded

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-rose#237]
### Problem

Some users want to be able to choose a different symlink dirs setup per workflow, see https://github.com/cylc/cylc-flow/issues/5418.
This can be done via the use of environment variables and Jinja2 in the global config, e.g.:
```
#!jinja2
[install]
    [[symlink dirs]]
        [[[hpc]]]
{% if environ["CYLC_SYMLINKS"] | default("x") == "A" %}
            run = $PROJECT_A
{% elif environ["CYLC_SYMLINKS"] | default("x") == "B" %}
            run = $PROJECT_B
{% else %}
            run = $DATADIR
{% endif %}
```

Where appropriate (depending on the use case) this could be configured at the site level or the user level.

In order for this to work you need to be able to configure an environment variable to be set both for `cylc install` (for localhost) and for `cylc play` (for remote hosts). It is already possible to define environment variables in `rose-suite.conf` which alter the scheduler environment:
https://metomi.github.io/rose/doc/html/api/configuration/suite.html#rose:conf:rose-suite.conf[env]
However, at present these do not apply when the global config is loaded.

### Proposed Solution

Ensure that environment variables set in `rose-suite.conf` apply when the global config is loaded (or reloaded if necessary).

**Comment by oliver-sanders** [comment]
Illustrative example:

```
# rose-suite.conf

[env]
CYLC_SYMLINKS=foo
```

```
# flow.cylc
```

```
# global.cylc
#!jinja2

[install]
    [[symlink dirs]]
        [[[hpc]]]
{% set cylc_symlinks = environ.get('CYLC_SYMLINKS', None) %}
{% if cylc_symlinks is None %}
    {# this will be the case when the global config is first loaded which is fine #}
{% else %}
    {# however, we need the env var to be set in time for the "cylc play" and "install" commands #}
{% endif %}
```

**Comment by oliver-sanders** [comment]
The solution is to wipe the cache on the global config within the cylc-rose plugin if any environment variables are set in the Rose config.

This will force the global config to be reloaded when the remainder of the play/install code is run after the plugin has finished.

I think this should go in pre-configure?

**Comment by wxtim** [comment]
Presumably https://github.com/cylc/cylc-flow/pull/5839 should not go in then?

**Comment by oliver-sanders** [comment]
No, that PR is fine.

This isn't about getting cylc-rose to process the global.cylc file, it's about getting cylc-rose to reset the cache of the global.cylc file. Confusing right!
