### ISSUE TITLE
template variables: malformed configuration section

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#246]
Spotted in the wild with a `rose stem` workflow.

The `cylc-install` optional config of an installed (`rose stem`) workflow contained both a `jinja2:suite.rc` section AND a `jinja2` section (missing the `:suite.rc` suffix).

The malformed section contained variables such as `RUN_NAMES` and `SITE` which are set by `cylc-rose` which subsequently did not take effect.

**Comment by oliver-sanders** [comment]
Likely related to #229

**Comment by wxtim** [comment]
@oliver-sanders  - do you know _how_ the user achieved this?

**Comment by oliver-sanders** [comment]
```ini
# rose-suite.conf

[jinja2:suite.rc]
answer=42
```

```console
$ rose stem
```
