### ISSUE TITLE
Consider allowable config sections in `rose-suite.conf`

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#25]
Currently cylc-rose will read `[jinja2:suite.rc]` and `[empy:suite.rc]` sections.

1. We should definitely allow a generic template vars section. What should we call this? (template_vars, templatevars, template vars)
2. Should consider allowing "jinja2:flow.cylc" and "empy:flow.cylc" as a sop to consistency? I'm actually not sure that it's really necessary, and might be confusing.

**Comment by oliver-sanders** [comment]
I think:

1. Yes - template variables?
2. No

**Comment by wxtim** [comment]
My conclusion too.

**Comment by wxtim** [comment]
This issue should have been closed with the merger of #30
