### ISSUE TITLE
log cylc-rose version on installation

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#318]
Would be good to record the cylc-rose version somewhere in the installation for debugging.

Ideas:
* `opt/rose-suite-cylc-install.conf`
* `log/install/?`

Would be a good idea to stick the metomi-rose version there too.

**Comment by wxtim** [comment]
I'd put it in `opt/rose-suite-cylc-install.conf` as a comment. I don't think we want to encourage people to use it as a feature, but why create an extra file.
