### ISSUE TITLE
compat mode ignored

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#319]
A bug which can be replicated by:

* Running a Cylc 7 workflow under Cylc 8 compat mode.
* Which contains an fcm_make task.
* And a `:finish` trigger.

This should do it:

```ini
# suite.rc
[scheduling]
  [[graph]]
    R1 = fcm_make:finish => fin
```

Due to the way the workflow config is loaded from the `log/config/flow-processed.cylc` file, the Cylc 7 compat mode check is not being performed correctly causing the config to think it is not in compat mode.

This check is performed automatically by `WorkflowConfig.__init__` so may require an upstream change to cylc-flow, hence 1.4.0.

Introduced by https://github.com/cylc/cylc-rose/pull/302

**Comment by wxtim** [comment]
I cannot replicate the bug with your example.

**Comment by oliver-sanders** [comment]
The error will be raised when the fcm_make task runs.

**Comment by wxtim** [comment]
Do we have an example of the error?
