### ISSUE TITLE
flaky tests

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#325]
The tests appear to have become flaky, maybe ~3 weeks back?!

https://github.com/cylc/cylc-rose/actions/workflows/tests.yml?query=branch%3Amaster

**Comment by wxtim** [comment]
@oliver-sanders: comparing the time of this post and looking at test failures in the week preceeding that: All these common failures are the one logged by Ronnie.

**Comment by wxtim** [comment]
Doesn't seem flaky - just run master 3 times in quick succession: https://github.com/cylc/cylc-rose/actions/workflows/tests.yml
