### ISSUE TITLE
Improved error/warning notifications

### ISSUE THREAD

**Issue by meteorpaul** [cylc/cylc-rose#335]
### Problem

Often, error messages or warnings are not entirely clear or they are absent. One such example is when `rose-suite.conf` is missing. There is no warning message.

### Proposed Solution

Improvement of error and warning messages; in the case of a missing `rose-suite.conf`, an explicit warning to say so. Such a message could say something like, "Warning, rose-suite.conf is missing".

**Comment by oliver-sanders** [comment]
Hi,

If you encounter a warning or error that is not clear, please comment this back to us so we can improve the message. We will have to rely on people such as yourself to point out warnings/errors that require improvement as it is not feasible for us to review every warning/error individually.


In the case of the `rose-suite.conf` file. This file is completely optional, some people choose to add this file to their workflows to take advantage of certain Rose features, such as the ability to configure template variables for use in the `flow.cylc` file. However, many people do not require these features in their workflow so do not use `rose-suite.conf` files in their workflows. This is perfectly reasonable, it is not an issue if a worklflow does no have a `rose-suite.conf` file, hence, no error or warning is raised.
