### ISSUE TITLE
Warn if `root dir` set

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-rose#37]
The `root dir` setting of `rose-suite.conf` was made obsolete by [cylc-flow PR #3688](https://github.com/cylc/cylc-flow/issues/3688).

If it is set cylc-rose should log a warning and do nothing.

@oliver-sanders in https://github.com/cylc/cylc-flow/issues/3819, does "do nothing" mean "fail with an error", or "ignore value with warning"?

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
I think "ignore with warning".
